### ISSUE TITLE
XMMS plugin (xmms-mp4)

### ISSUE THREAD

**Issue by app4soft** [knik0/faad2#169]
Is it still possible compile `xmms-mp4` with latest `faad2` for Linux?

- https://github.com/Opendigitalradio/faad2/tree/master/plugins/xmms

Target Linux distro: _antiX-23_ (Debian 12 bookworm), amd64.

- https://antixlinux.com/antix-23-beta2-iso-files-for-testing/

As I see, all plugins dropped from your repo, but after `2.10.1` release (latest):

- https://github.com/knik0/faad2/pull/136

**Comment by eustas** [comment]
Before plugin was dropped things were complicated: that plugin was depending on xmms, and xmms was depending on faad.

If I understand correctly that is because xmms already have faad plugin: https://github.com/xmms2/xmms2-stable/blob/master/src/plugins/faad/faad.c

In case it is not enough, dropped code could be moved to xmms project (i.e. there will be only one dependency xmms -> faad).

**Comment by app4soft** [comment]
> If I understand correctly that is because xmms already have faad plugin: https://github.com/xmms2/xmms2-stable/blob/master/src/plugins/faad/faad.c

No, I mean a "xmms-mp4" plugin for XMMS 1.2.11 (not "xmms2-plugin-mp4" for XMMS2).

- http://xmms.org/download.php
- https://slackbuilds.org/repository/14.2/audio/xmms-mp4/
- Fixing AAC/MP4/M4A playback for xmms on x86_64 (amd64) - http://wp.xin.at/archives/3791

**Comment by fabiangreffrath** [comment]
Sorry, but we won't be providing the plug-in for the original xmms anymore. It has been removed from Debian in 2007, and more viable alternatives exist in xmms2 and audacious. If there is a project available to keep this plug-in alive, it's their responsibility to cope with faad's API changes.
