### ISSUE TITLE
error: conflicting types for 'lrintf'

### ISSUE THREAD

**Issue by ryandesign** [knik0/faad2#188]
faad2 2.11.0 doesn't build for i386 on macOS:

```
In file included from libfaad/bits.c:31:
In file included from libfaad/common.h:377:
In file included from /usr/include/math.h:28:
/usr/include/architecture/i386/math.h:379:17: error: conflicting types for 'lrintf'
extern long int lrintf ( float );
                ^
libfaad/common.h:342:23: note: previous definition is here
    static INLINE int lrintf(float f)
                      ^
```

The code does this:

https://github.com/knik0/faad2/blob/18709102177b3a343bdcc307632c19e5a0ce1c47/libfaad/common.h#L337-L342

Looks like the intention is to define `lrintf` only if the system doesn't have it, but this doesn't work because `HAVE_LRINTF` doesn't ever get defined. I find no occurrences of this macro in any other files. There also seems to be confusion about whether it's called `HAVE_LRINTF` or `HAS_LRINTF`. The problem is avoided on x86_64 and arm64 systems because the code checks for `__i386__`.

This was originally [reported to MacPorts](https://trac.macports.org/ticket/68663) by @RobK88.

**Comment by ryandesign** [comment]
I should add that we are building with cmake, and that this is new for MacPorts for faad2 2.11.0; previously we were building with autotools. I presume that autotools would define `HAVE_LRINTF` but that cmake does not.

This is one of those problems with maintaining two build systems. It's a lot of work to ensure that they both function the same. You may want to consider dropping all but one build system.

**Comment by smu-ggl** [comment]
Hmm, https://github.com/knik0/faad2/commit/1001f9576cbb29242671c489cd861de61cfe08e2 doesn't seem to fix this for me.

I created a copy of the Debian package 2.11.0-1 with that commit added. I get:
```
-- Looking for lrintf
-- Looking for lrintf - not found
```

And yet later:
```
In file included from /<<PKGBUILDDIR>>/libfaad/common.h:377,
                 from /<<PKGBUILDDIR>>/libfaad/bits.c:31:
/usr/include/i386-linux-gnu/bits/mathcalls.h:317:1: error: conflicting types for ‘lrintf’; have ‘long int(float)’
  317 | __MATHDECL (long int,lrint,, (_Mdouble_ __x));
      | ^~~~~~~~~~
/<<PKGBUILDDIR>>/libfaad/common.h:342:23: note: previous definition of ‘lrintf’ with type ‘int(float)’
  342 |     static INLINE int lrintf(float f)
      |                       ^~~~~~
```

To me this looks like the check_symbol_exists check is somehow missing the definition in math.h (via unconditional include of bits/mathcalls.h)

What confuses me a little is that if I run `cpp t.h` with t.h being just `#include<math.h>`, I do get this:
```
extern long int lrintf (float __x) __attribute__ ((__nothrow__ , __leaf__)); extern long int __lrintf (float __x) __attribute__ ((__nothrow__ , __leaf__));
```
So it looks to me as if the expected function is defined. (I'm not a C expert by any means, but this looks to me as if the cmake function *should* find that symbol.

Here is the code I think the cmake function would generate:

```
#include<math.h>
int main(int argc, char** argv)
{
  (void)argv;
#ifndef lrintf
  return ((int*)(&lrintf))[argc];
#else
    (void)argc;
  return 0;
#endif
}
```
And when I try to compile that, I get:
```
# gcc -lm -o /tmp/t /tmp/t.c 
/usr/bin/ld: /tmp/cchDKEa6.o: in function `main':
t.c:(.text+0x15): undefined reference to `lrintf'
collect2: error: ld returned 1 exit status
```

(Same when omitting the `-lm`.)

However, libm seems to properly provide the symbol (as seen via `nm -gD /usr/lib/i386-linux-gnu/libm.so`). Also the compile works if I link to libm statically: `# gcc -o /tmp/t /tmp/t.c /usr/lib/i386-linux-gnu/libm.a`

Somewhat unrelated to the failure: Shouldn't the definition in libfaad/common.h also use `long int` instead of `int`? The `l` in `lrintf` seems to explicitly mean `long`, no?
